arcus-azure/arcus.testing

- .github/CODEOWNERS
> Chore: update CODEOWNERS

- build/nuget-release.yml
> Fix - update to correct GitHub repo

- build/variables/build.yml
- src/Arcus.Testing.Logging/Arcus.Testing.Logging.csproj
- src/Arcus.Testing.Tests.Integration/Arcus.Testing.Tests.Integration.csproj
- src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj
> Chore - use xunit.abstractions instead

- src/Arcus.Testing.Logging/Arcus.Testing.Logging.csproj
- src/Arcus.Testing.Logging/CustomLoggerProvider.cs
- src/Arcus.Testing.Security.Providers.InMemory/Arcus.Testing.Security.Providers.InMemory.csproj
Treat warnings as errors.
Relates to https://github.com/arcus-azure/arcus/issues/196
> chore: treat warnings as errors

- src/Arcus.Testing.Logging/Arcus.Testing.Logging.csproj
- src/Arcus.Testing.Security.Providers.InMemory/Arcus.Testing.Security.Providers.InMemory.csproj
- src/Arcus.Testing.Tests.Integration/Arcus.Testing.Tests.Integration.csproj
- src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj
Upgrade packages towards .NET 6.
Relates to https://github.com/arcus-azure/arcus/issues/188
> feat: upgrade towards net6.0

- src/Arcus.Testing.Logging/Arcus.Testing.Logging.csproj
- src/Arcus.Testing.Security.Providers.InMemory/Arcus.Testing.Security.Providers.InMemory.csproj
Adds the GitHub README file to the NuGet package generation of the projects.
Relates to arcus-azure/arcus#209
> chore: add readme to nuget pkg

- src/Arcus.Testing.Logging/Arcus.Testing.Logging.csproj
- src/Arcus.Testing.Security.Providers.InMemory/Arcus.Testing.Security.Providers.InMemory.csproj
Adds package readme project tag in project files.
Relates to https://github.com/arcus-azure/arcus/issues/209
> chore: add package readme project tag

- docs/preview/features/inmemory-secret-provider.md
- docs/v0.2/features/inmemory-secret-provider.md
- docs/v0.3/features/inmemory-secret-provider.md
- docs/v0.4/features/inmemory-secret-provider.md
- docs/v0.4/features/logging.md
- docs/v0.4/index.md
We forgot to update the internal feature docs for v0.4.
Fixes that.
> docs: publish v0.4 feature docs

- .github/CODEOWNERS
Sets the testing team as code-owners.
> chore: set testing team as code owners

- src/Arcus.Testing.Logging/NUnitTestLogger.cs
- src/Arcus.Testing.Logging/XunitTestLogger.cs
- src/Arcus.Testing.Tests.Unit/Logging/NUnitTestLoggerTests.cs
* Add an generic `ILogger<TCategoryName>` xUnit implementation
* Add an `ILogger`/`ILogger<TCategoryName>` NUnit implementation
Closes #99
> feat: add missing nunit/xunit loggers

- .github/CODEOWNERS
Should be the testing team, instead of individual persons.
> chore: correct code owners w/ recent changes

- docs/preview/02-Features/assertion.md
- docs/preview/03-Guidance/migrate-from-testing-framework-to-arcus-testing-v1.0.md
- src/Arcus.Testing.Assert/AssertXslt.cs
- src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj
- src/Arcus.Testing.Tests.Unit/Assert_/AssertXsltTests.cs
- src/Arcus.Testing.Tests.Unit/Assert_/Resources/xslt-transform.xml-csv.sample.input.xml
- src/Arcus.Testing.Tests.Unit/Assert_/Resources/xslt-transform.xml-csv.sample.output.csv
- src/Arcus.Testing.Tests.Unit/Assert_/Resources/xslt-transform.xml-csv.sample.transformer.xslt
Added XSLT XML-CSV transformation, plus renamed the `TransformTo...` to be more clear of the output.
Follow-up #102
> feat: add assert xslt csv transformation

- docs/preview/03-Guidance/migrate-from-testing-framework-to-arcus-testing-v1.0.md
Add the use of XSLT sequential transformation and how to load resource files in the test project.
Closes #134
> docs: add xslt sequential & resource usage in migration guide

- .github/workflows/code-coverage.yml
Upgrade code coverage GH action.
> chore: upgrade code coverge action

- samples/Arcus.Testing.Sample.TestingFrameworkMigration/Arcus.Testing.Sample.TestingFrameworkMigration.csproj
- samples/Arcus.Testing.Sample.TestingFrameworkMigration/MSTestIntegrationTest.cs
- samples/Arcus.Testing.Sample.TestingFrameworkMigration/NUnitIntegrationTest.cs
- samples/Arcus.Testing.Sample.TestingFrameworkMigration/OutputComparison/XsltHelper_To_AssertXslt.cs
- samples/Arcus.Testing.Sample.TestingFrameworkMigration/XunitIntegrationTest.cs
Adds different integration test base classes for the different kind of mostly-used testing frameworks.
> chore: add diff integration base classes for diff test frameworks

- docs/docusaurus.config.js
Adds `diff` as another code style language.
> docs: add `diff` as additional code style lang

- build/nuget-release.yml
Make sure that the link text matches the link.
> chore: make sure we reference a good package in the release pipeline

- docs/preview/02-Features/04-Storage/01-storage-account.mdx
- docs/preview/02-Features/04-Storage/02-cosmos.mdx
- src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlContainer.cs
- src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlItem.cs
- src/Arcus.Testing.Storage.Table/TemporaryTable.cs
- src/Arcus.Testing.Storage.Table/TemporaryTableEntity.cs
Add the necessary changes in the feature documentation to explain the required role permissions in certain scenarios, plus make sure that we always fail on any of the (even) rudimentairy interactions so that any of these missing permissions gets flagged immediately and we never(!) have false positives.
Closes #217 
Closes #218
> docs: explain required role-permissions

- src/Arcus.Testing.Storage.Cosmos/Arcus.Testing.Storage.Cosmos.csproj
- src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbCollection.cs
- src/Arcus.Testing.Tests.Integration/Storage/Fixture/MongoDbTestContext.cs
- src/Arcus.Testing.Tests.Integration/Storage/TemporaryMongoDbDocumentTests.cs
Invictus is working on upgrading to MongoDb v3 (they had some perf issues with v2); and due to their not-so-quality package management, they released lots of versions in a short period of time.
Best that we also upgrade to this new version.
Closes #254
> chore: upgrade to mongodb v3 (❗)

- README.md
- docs/preview/01-index.md
Sync up the short introduction on the site with the `README.md` file in the repository
> docs(readme): provide meaningful short description in readme

- .github/workflows/bump-docs-version.yml
Adds a GitHub workflow that automatically runs the `npm` command that generates a new documentation version, plus provides a pull request with the changes.
> docs(setup): auto-bump new docs version workflow

- src/Arcus.Testing.Storage.Blob/TemporaryBlobContainer.cs
- src/Arcus.Testing.Storage.Blob/TemporaryBlobFile.cs
Use net8.0 arg constructs in blob library
> chore(blob): use net8.0 arg constructs in blob library

- src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbCollection.cs
- src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbDocument.cs
- src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlContainer.cs
chore(assert): use net8.0 arg constructs in cosmos library
> chore(cosmos): use net8.0 arg constructs in cosmos library

- README.md
Let's be proud of our current quality score, and place the badge on the `README.md`.
> docs(ci): add sonar qube quality gate badge to README.md

- CODE_OF_CONDUCT.md
Adds a Code of Conduct to the repository, so that we explicitly state the inclusive environment in which we work.
> docs(root): CODE_OF_CONDUCT.md

- src/Arcus.Testing.Core/Arcus.Testing.Core.csproj
- src/Arcus.Testing.Core/AsyncDisposable.cs
- src/Arcus.Testing.Core/DisposableCollection.cs
- src/Arcus.Testing.Core/Poll.cs
- src/Arcus.Testing.Core/ResourceDirectory.cs
- src/Arcus.Testing.Core/TemporaryEnvironmentVariable.cs
- src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj
The Roslyn code analyzers notified us about some improvements. These improvements in this PR are applied in the `.Core` library:
✔️ Use `.ConfigureAwait(false)` in test infrastructure code, for more consistency between local/remote testing.
✔️ Use `IReadOnlyCollection` for `DisposableCollection` to make it a 'full' collection which provides a more composable/extendible approach on teardown (custom dispose, more control, retry options...)
✔️ `[LoggerMessage]` mostly marketed as a more performance logging, but also in our case helps with centralizing log messages, as especially in case of setup/teardown, we want to have the same structure.
Relates to #429
> chore(analysis): applied code analysis results in core

- src/Arcus.Testing.Storage.Blob/Arcus.Testing.Storage.Blob.csproj
- src/Arcus.Testing.Storage.Blob/TemporaryBlobContainer.cs
- src/Arcus.Testing.Storage.Blob/TemporaryBlobFile.cs
Applies the recommended code analysis to the `.Blob` library. This is mostly about the logger message templates that can be made as 'source generated log methods' for improved performance. Though, in our case, it is also about centralizing the log statements so it is more easily maintained (setup/teardown in same style); plus now we can reuse even some log messages.
> chore(analysis): applied code analysis results in blob storage

- src/Arcus.Testing.Assert/Arcus.Testing.Assert.csproj
- src/Arcus.Testing.Assert/AssertCsv.cs
- src/Arcus.Testing.Assert/AssertJson.cs
- src/Arcus.Testing.Assert/AssertXml.cs
- src/Arcus.Testing.Assert/AssertXslt.cs
- src/Arcus.Testing.Assert/Failure/ReportBuilder.cs
Adds `Recommended` code analysis for Rosyln to the `.Assert` library and apply the necessary improvements throughout. This is partially related to the #432 and #429 .
> chore(analysis): applied code analysis results in assert

- src/Arcus.Testing.Storage.Cosmos/Arcus.Testing.Storage.Cosmos.csproj
- src/Arcus.Testing.Storage.Cosmos/MongoDbConnection.cs
- src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbCollection.cs
- src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbDocument.cs
- src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlContainer.cs
- src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlItem.cs
Apply all the .NET Roslyn analyzers to the Cosmos project.
Relates to #429
> chore(cosmos): apply roslyn analysers to cosmos project

- src/Arcus.Testing.Messaging.ServiceBus/Arcus.Testing.Messaging.ServiceBus.csproj
- src/Arcus.Testing.Messaging.ServiceBus/ServiceBusMessageFilter.cs
- src/Arcus.Testing.Messaging.ServiceBus/TemporaryQueue.cs
- src/Arcus.Testing.Messaging.ServiceBus/TemporaryTopic.cs
- src/Arcus.Testing.Messaging.ServiceBus/TemporaryTopicSubscription.cs
Apply `All` Roslyn analyzers on the Service Bus project.
Relates to #429
> chore(sb): apply roslyn analysers to service-bus project

- src/Arcus.Testing.Assert/Arcus.Testing.Assert.csproj
- src/Arcus.Testing.Assert/AssertCsv.cs
- src/Arcus.Testing.Assert/AssertXml.cs
- src/Arcus.Testing.Assert/Failure/AssertionException.cs
- src/Arcus.Testing.Assert/Failure/CsvException.cs
- src/Arcus.Testing.Assert/Failure/EqualAssertionException.cs
- src/Arcus.Testing.Assert/Failure/ReportBuilder.cs
Apply `All` Roslyn analyzers on Assert project.
Relates to #455
> chore(assert): apply roslyn analysers to assert project
