arcus-azure/arcus.testing

docs/preview/logging.md, src/Arcus.Testing.Logging/Arcus.Testing.Logging.csproj, src/Arcus.Testing.Logging/CustomLoggerProvider.cs, src/Arcus.Testing.Logging/Extensions/ILoggerBuilderExtensions.cs, src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj, src/Arcus.Testing.Tests.Unit/Logging/CustomLoggerProviderTests.cs, src/Arcus.Testing.Tests.Unit/Logging/ILoggerBuilderExtensionsTests.cs, src/Arcus.Testing.Tests.Unit/Logging/SpyLoggerTests.cs
Provides a test infrastructure so that we can write diagnostic test messages to the xUnit test output from .NET Core apps.
Relates to #25
=> Feature - add xUnit test logging for .NET Core apps

docs/features/logging.md, docs/index.md, docs/preview/features/logging.md, docs/preview/index.md, docs/v0.1/features/logging.md, docs/v0.1/index.md
Add missing `using` statements to the feature docs.
Relates to https://github.com/arcus-azure/arcus/issues/107
=> Docs - add missing 'using's to the feature docs

docs/preview/features/inmemory-secret-provider.md, docs/preview/index.md, src/Arcus.Testing.Security.Providers.InMemory/Arcus.Testing.Security.Providers.InMemory.csproj, src/Arcus.Testing.Security.Providers.InMemory/Extensions/SecretStoreBuilderExtensions.cs, src/Arcus.Testing.Security.Providers.InMemory/InMemoryCachedSecretProvider.cs, src/Arcus.Testing.Security.Providers.InMemory/InMemorySecretProvider.cs, src/Arcus.Testing.Tests.Integration/Arcus.Testing.Tests.Integration.csproj, src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj, src/Arcus.Testing.Tests.Unit/Blanks.cs, src/Arcus.Testing.Tests.Unit/Security/InMemoryCachedSecretProviderTests.cs, src/Arcus.Testing.Tests.Unit/Security/InMemorySecretProviderTests.cs, src/Arcus.Testing.Tests.Unit/Security/SecretStoreBuilderExtensionsTests.cs, src/Arcus.Testing.sln
Adds a in-memory `ISecretProvider` implementation for testing purposes with necessary extensions to easily register the instance in the secret store.
Closes #34
=> Feature - add in-memory secret provider for the Arcus secret store

src/Arcus.Testing.Logging/XunitTestLogger.cs
When a failure occurred, it wasn't always shown in the test output. This will make sure it's always shown if it's passed along.
Closes #38
=> feat: add exception explicitly to the test output

docs/preview/features/logging.md, src/Arcus.Testing.Logging/Arcus.Testing.Logging.csproj, src/Arcus.Testing.Logging/InMemoryLogSink.cs, src/Arcus.Testing.Logging/InMemoryLogger.cs, src/Arcus.Testing.Tests.Unit/Logging/InMemoryLogSinkTests.cs
Add Serilog log sink which in-memory collects the log emits so they can be asserted.
This is especially useful when testing opt-in functionality regarding telemetry.
=> feat: add serilog in-memory log sink

build/variables/build.yml, src/Arcus.Testing.Logging/Arcus.Testing.Logging.csproj, src/Arcus.Testing.Security.Providers.InMemory/Arcus.Testing.Security.Providers.InMemory.csproj, src/Arcus.Testing.Tests.Integration/Arcus.Testing.Tests.Integration.csproj, src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj
Updates the projects from `netstandard2.0` to `netstandard2.1`.
Relates to https://github.com/arcus-azure/arcus/issues/106
=> chore: update to netstandard2.1

src/Arcus.Testing.Security.Providers.InMemory/Arcus.Testing.Security.Providers.InMemory.csproj
Use NuGet version ranges for Arcus packages.
Relates to https://github.com/arcus-azure/arcus/issues/129
=> chore: use version ranges for Arcus deps

docs/preview/features/servicebus-messsage-pump.md, src/Arcus.Testing.Messaging.Pumps.ServiceBus/Arcus.Testing.Messaging.Pumps.ServiceBus.csproj, src/Arcus.Testing.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Testing.Messaging.Pumps.ServiceBus/IAzureServiceBusMessageProducer.cs, src/Arcus.Testing.Messaging.Pumps.ServiceBus/TestAzureServiceBusMessageProducer.cs, src/Arcus.Testing.Messaging.Pumps.ServiceBus/TestServiceBusMessagePump.cs, src/Arcus.Testing.Messaging.Pumps.ServiceBus/TestServiceBusReceiver.cs, src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj, src/Arcus.Testing.Tests.Unit/Messaging/ServiceBus/Fixture/Container.cs, src/Arcus.Testing.Tests.Unit/Messaging/ServiceBus/Fixture/Order.cs, src/Arcus.Testing.Tests.Unit/Messaging/ServiceBus/Fixture/OrderAzureServiceBusMessageHandler.cs, src/Arcus.Testing.Tests.Unit/Messaging/ServiceBus/Fixture/Product.cs, src/Arcus.Testing.Tests.Unit/Messaging/ServiceBus/Fixture/Shipment.cs, src/Arcus.Testing.Tests.Unit/Messaging/ServiceBus/Fixture/ShipmentAzureServiceBusMessageHandler.cs, src/Arcus.Testing.Tests.Unit/Messaging/ServiceBus/TestServiceBusMessagePumpTests.cs, src/Arcus.Testing.sln
Adds a test version of the Azure Service Bus message pump so that messages from Service Bus can be simulated and custom message handlers can be tested together.
Closes #
=> feat: add test az servicebus message pump

docs/preview/features/eventhubs-messsage-pump.md, docs/preview/features/servicebus-messsage-pump.md, src/Arcus.Testing.Messaging.Pumps.EventHubs/Arcus.Testing.Messaging.Pumps.EventHubs.csproj, src/Arcus.Testing.Messaging.Pumps.EventHubs/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Testing.Messaging.Pumps.EventHubs/IAzureEventHubsMessageProducer.cs, src/Arcus.Testing.Messaging.Pumps.EventHubs/TestAzureEventHubsMessageProducer.cs, src/Arcus.Testing.Messaging.Pumps.EventHubs/TestEventHubsMessagePump.cs, src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj, src/Arcus.Testing.Tests.Unit/Messaging/EventHubs/Fixture/SensorReading.cs, src/Arcus.Testing.Tests.Unit/Messaging/EventHubs/Fixture/SensorReadingAzureEventHubsMessageHandler.cs, src/Arcus.Testing.Tests.Unit/Messaging/EventHubs/Fixture/SensorTelemetry.cs, src/Arcus.Testing.Tests.Unit/Messaging/EventHubs/Fixture/SensorTelemetryAzureEventHubsMessageHandler.cs, src/Arcus.Testing.Tests.Unit/Messaging/EventHubs/TestEventHubsMessagePumpTests.cs, src/Arcus.Testing.sln
Adds a test version of an EventHubs message pump so that message handlers can be tested with ease.
Closes #69
=> feat: add test event hubs message pump

build/ci-build.yml
Use the new `main` branch in the CI build.
Relates to https://github.com/arcus-azure/arcus/issues/169
=> chore: update ci build w/ main branch

docs/preview/features/logging.md, src/Arcus.Testing.Logging/Extensions/LoggerSinkConfigurationExtensions.cs, src/Arcus.Testing.Logging/XunitTestLogSink.cs, src/Arcus.Testing.Tests.Unit/Logging/LoggerSinkConfigurationExtensionsTests.cs
Multiple Arcus repo's are dupicating an implementation of a Serilog xUnit test log sink.
Adding it to the Arcus Testing repo will remove this duplication and simplify the test projects.
=> feat: add serilog xunit test log sink

docs/preview/features/inmemory-secret-provider.md, src/Arcus.Testing.Security.Providers.InMemory/Arcus.Testing.Security.Providers.InMemory.csproj, src/Arcus.Testing.Security.Providers.InMemory/InMemorySecretProvider.cs, src/Arcus.Testing.Tests.Unit/Security/InMemorySecretProviderTests.cs, src/Arcus.Testing.Tests.Unit/Security/SecretStoreBuilderExtensionsTests.cs
Add synchronous secret retrieval to the testing in-memory secret provider.
=> feat: add sync secret retrieval to in-memory secret provider

src/Arcus.Testing.Logging/Extensions/LoggerSinkConfigurationExtensions.Deprecated.cs, src/Arcus.Testing.Tests.Unit/Logging/LoggerSinkConfigurationExtensionsTests.cs
Correct the xUnit Serilog sink extension to the correct namespace: `Serilog.Configuration`.
Closes #81
=> fix: correct xunit serilog extension namespace

build/ci-build.yml, build/nuget-release.yml, build/variables/build.yml, src/Arcus.Testing.Logging/Arcus.Testing.Logging.csproj, src/Arcus.Testing.Messaging.Pumps.EventHubs/Arcus.Testing.Messaging.Pumps.EventHubs.csproj, src/Arcus.Testing.Messaging.Pumps.EventHubs/TestEventHubsMessagePump.cs, src/Arcus.Testing.Messaging.Pumps.ServiceBus/Arcus.Testing.Messaging.Pumps.ServiceBus.csproj, src/Arcus.Testing.Messaging.Pumps.ServiceBus/TestServiceBusMessagePump.cs, src/Arcus.Testing.Security.Providers.InMemory/Arcus.Testing.Security.Providers.InMemory.csproj, src/Arcus.Testing.Tests.Integration/Arcus.Testing.Tests.Integration.csproj, src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj
Use new Arcus Security+Messaging w/ .NET 8 support.
=> chore: add net8.0 support

README.md
Streamline the current `README.md` with the other Arcus repositories now that it can be used outside the internal Arcus ecosystem (points to the documentation site instead of placing the installation sections directly in the `README.md`).
=> chore: streamline readme w/ other repo's

docs/preview/02-Features/assertion.md, src/Arcus.Testing.Assert/AssertJson.cs, src/Arcus.Testing.Assert/AssertXml.cs, src/Arcus.Testing.Assert/AssertXslt.cs, src/Arcus.Testing.Tests.Unit/Assert_/AssertJsonTests.cs, src/Arcus.Testing.Tests.Unit/Assert_/AssertXmlTests.cs, src/Arcus.Testing.Tests.Unit/Assert_/Fixture/TestJson.cs, src/Arcus.Testing.Tests.Unit/Assert_/Fixture/TestXml.cs
Makes sure that XML attributes and JSON array values are compared by default without taking the order of their presence into account. To override this, a new option is added to the assertion options.
This is the last feature in the Testing Framework's comparisons that was missing from Arcus.
Closes #101
=> feat: ignore order for assert xml & json

src/Arcus.Testing.Tests.Unit/Assert_/AssertJsonTests.cs, src/Arcus.Testing.Tests.Unit/Assert_/AssertXmlTests.cs, src/Arcus.Testing.Tests.Unit/Assert_/Fixture/TestXml.cs
Corrects the XML inputs of the test assertion to not include `&` and make sure that upon shuffling all the child elements are also shuffled.
In both cases there was a rare instance that a generated value contained an `&` or was 'not enough' shuffled to make the test succeed.
This PR also make sure that there is more logging in both tests so that upon failure, we clearly see the test inputs; this to more quickly spot any future failures.
Follow-up of #101
=> test: correct xml/json test inputs

src/Arcus.Testing.Assert/Arcus.Testing.Assert.csproj, src/Arcus.Testing.Assert/AssertCsv.cs, src/Arcus.Testing.Assert/AssertJson.cs, src/Arcus.Testing.Core/Arcus.Testing.Core.csproj, src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj, src/Arcus.Testing.Tests.Unit/Assert_/AssertJsonTests.cs, src/Arcus.Testing.Tests.Unit/Assert_/Fixture/TestCsv.cs, src/Arcus.Testing.Tests.Unit/Core/DisposableCollectionTests.cs
Adds .NET 6 support to assertion library, for more eaiser migration.
PR contains changes to make the current functionality work both in .NET 6 & 8. It uses more broadly used functionality instead of .NET 8-specific ones.
Closes #114
Created issue #118 to remove it back.
=> chore: add net6.0 support for assertion library

docs/preview/02-Features/assertion.md, src/Arcus.Testing.Assert/AssertCsv.cs, src/Arcus.Testing.Tests.Unit/Assert_/AssertCsvTests.cs, src/Arcus.Testing.Tests.Unit/Assert_/Fixture/TestCsv.cs
Adds the escape and quote functionality to the loading of CSV tables.
* `Escape` lets you either escape the special separator character or the quote character,
* `Quote` lets you mark a cell value as a `string`, which means that occurences of the separator or escaped quote characters are considered part of the text value.
Closes #117
=> feat: assert csv w/ escape & quote

docs/preview/02-Features/core.md, src/Arcus.Testing.Core/Poll.cs, src/Arcus.Testing.Tests.Unit/Core/PollTests.cs
Introduce reusable `Poll`ing mechanism as an assertion-like safeguard before interacting with external resources, or as an assertion by itself.
Closes #113
=> feat: introduce reusable polling mechanism

build/nuget-release.yml
Seemed like the unit tests were not yet part of the requirements in the release pipeline.
Fixed that here.
=> fix: add unit tests dependencies to release

.github/workflows/code-coverage.yml, README.md
Adds code coverage reporting to the repository that reports to Coverlet and shows the coverage percentage in the repo's root `README.md` with a badge.
=> chore: add code coverage reporting

src/Arcus.Testing.Core/TestConfig.cs, src/Arcus.Testing.Tests.Integration/Core/TestConfigTests.cs
Mark the main `appsettings.json` file as optional by-design in the `TestConfig` for more easily access and user-friendliness.
Follow-up of #92
=> fix: mark main appsettings testconfig optional

src/Arcus.Testing.Assert/AssertCsv.cs, src/Arcus.Testing.Tests.Unit/Assert_/AssertCsvTests.cs
Adds an additional condition to the Assert CSV that makes sure that any text value with spaces is always considered text.
Follow-up: #115
=> fix: compare csv ints w/ spaces as text

docs/preview/02-Features/core.md, src/Arcus.Testing.Core/DisposableCollection.cs, src/Arcus.Testing.Core/ResourceDirectory.cs, src/Arcus.Testing.Core/TestConfig.cs, src/Arcus.Testing.Tests.Integration/Core/Fixture/CustomTestConfig.cs, src/Arcus.Testing.Tests.Integration/Core/ResourceDirectoryTests.cs, src/Arcus.Testing.Tests.Integration/Core/TestConfigTests.cs, src/Arcus.Testing.Tests.Unit/Assert_/AssertXmlTests.cs, src/Arcus.Testing.Tests.Unit/Core/DisposableCollectionTests.cs
Adds some improvements to the core library that were all related to improved adoptation - were found when trying to include into Invictus test suite.
* Provide a `DisposableCollection.AddRange` method to add multiple disposable instances at once, this is especially useful when you deal with many of the same test fixture - like several temporary environment variables.
* Provide a `ReadFileText/BytesByPattern` method to pass in a search pattern to find a resource file instead of obligated for the full name - lessens the dependanbility on the test suite to know the exact names when it can just pass in `*.xslt` in a certain folder.
* Make the `TestConfig` open for extensibility by accepting child implementations by using the `TestConfig` as a base parent class - this helps when you want …
=> feat: add adoptation improvements on core functionality

src/Arcus.Testing.Tests.Unit/Core/PollTests.cs
Remove the need for an index field and do randomization of sabotage exceptions based on probability instead.
Closes #133
=> chore: remove index field in polling tests

src/Arcus.Testing.Messaging.Pumps.ServiceBus/TestServiceBusReceiver.cs
The new .NET 8 is also in need of overriding these properties, otherwise the logs are poluted with failures.
=> fix: remove any net6.0-specific directives

src/Arcus.Testing.Core/Poll.cs, src/Arcus.Testing.Tests.Unit/Core/PollTests.cs
Polling w/o exception but with a until targets should take all of them instead of any.
> It's very confusing and easy to get wrong as you have to think in reverse.
=> fix: poll w/ solely until predicate

src/Arcus.Testing.Core/AsyncDisposable.cs
Add async overload for async disposable for more easier adoptation.
Closes #146 
> Tested implicitly too as it delegates overloads.
=> feat: add async overload for async disposable

src/Arcus.Testing.Core/Poll.cs, src/Arcus.Testing.Tests.Unit/Assert_/AssertCsvTests.cs, src/Arcus.Testing.Tests.Unit/Core/PollTests.cs
Sometimes, the target could be interact with in a synchronous manner. To ease the usage for developers, we could provide sync overloads, so they do not have to use `Task.FromResult/CompletedTask`.
Closes #149
=> feat: add sync overloads for poll targets

src/Arcus.Testing.Core/Poll.cs, src/Arcus.Testing.Tests.Unit/Core/PollTests.cs
When polling for no result, it should `await` the asynchronous operation, not continuing.
=> fix: correct poll w/o result

build/ci-build.yml, build/deploy-test-resources.yml, build/nuget-release.yml, build/templates/integration-tests.yml, build/templates/smoke-tests.ps1, build/templates/test-resources.bicep, build/templates/unit-tests.yml, build/variables/test.yml
As prepartion for the upcoming Arcus.Testing storage functionality, we should make sure that we have a Storage Account in the new tenant to interact with during local/CI testing.
Relates to #93
=> chore: deploy storage test resources

src/Arcus.Testing.Tests.Unit/Assert_/AssertXmlTests.cs, src/Arcus.Testing.Tests.Unit/Core/PollTests.cs
Stabelizes unit tests by making sure that unique/diff values are indeed unique and giving the poll tests a bit more playroom in terms of retrying.
Closes #159 
Closes #153
=> chore: stabelize unit tests

docs/preview/02-Features/02-assertion.md, src/Arcus.Testing.Assert/AssertCsv.cs, src/Arcus.Testing.Tests.Unit/Assert_/AssertCsvTests.cs, src/Arcus.Testing.Tests.Unit/Assert_/Fixture/TestCsv.cs
Added option `IgnoreColumnIndex(int index)` that allows to ignore a column via its index. Useful when headers are missing and we still want to ignore a column.
Added a validation to make sure that validation fails when `opt.ColumnOrder` is set to `AssertCsvOrder.Ignore` and it is used together with `IgnoreColumnIndex(int index)`.
Closes #155
=> feat: Add support to ignore column via index when CSV Headers are missing

docs/preview/02-Features/02-assertion.md
Relates to [issue #154](https://github.com/arcus-azure/arcus.testing/issues/154)
=> docs: Added information about IgnoreNode using JSON path not supported

README.md
We should use the correct example NuGet package in the README, otherwise the NuGet package does not show the most recent package version.
=> docs: use correct example package for NuGet badge in README

src/Arcus.Testing.Assert/AssertCsv.cs, src/Arcus.Testing.Assert/AssertJson.cs, src/Arcus.Testing.Assert/AssertXml.cs
Saw that not all assertion failures include the related available options in their failure message. Having the options there can help with pinpointing the problem.
=> chore: add all related options to assert failure messge

build/templates/publish-coverage.yml, src/Arcus.Testing.Tests.Unit/Core/PollTests.cs
Forgot to add a condition to the steps related to publishing to a PR to only run when triggered by a PR; otherwise, runs on `main` will fail.
Follow-up of #170
=> chore: only publish code coverage comment when building on PR

README.md
The `README.md` file did not point to the correct NuGet package in the nuget badge.
=> chore: fix nuget badge w/ correct url

docs/preview/03-Guidance/migrate-from-testing-framework-to-arcus-testing-v1.0.mdx
Updates the migration guide from the Testing Framework to include our new Table & Cosmos NoSql functionality.
=> docs: add table & cosmos nosql to migration guide

src/Arcus.Testing.Tests.Integration/Storage/TemporaryBlobContainerTests.cs
When a random `BlobNameFilter` is created to match against a blob, only the first 5 characters were sometimes taken, but since the blob names start with `blob...`, the chance that the appending GUID starts with the same character is rather big.
This PR makes this a bit more stable by taking a bigger portion of the name to match.
=> chore: super rare blob name matching

README.md
We should use the `main` branch only to show the code coverage information in the `README.md` file.
=> docs: use `main` branch to show code-coverage in `README.md`

docs/preview/02-Features/06-Integration/01-data-factory.mdx, src/Arcus.Testing.Integration.DataFactory/TemporaryDataFlowDebugSession.cs, src/Arcus.Testing.Tests.Integration/Integration/DataFactory/Fixture/TemporaryDataFactoryDataFlow.cs, src/Arcus.Testing.Tests.Integration/Integration/DataFactory/RunDataFlowTests.cs, src/Arcus.Testing.Tests.Unit/Integration/DataFactory/RunDataFlowTests.cs
- Added dataset parameters to dataflow debug settings 
- For information, debugSettings.DatasetParameters is of type BinaryData. Data is basically a JSON representation of a Dictionary<string, Dictionary<string, object>>, where the high level dictionary contains the keys of the dataset names, and the low level dictionary contains the actual dataset parameter keys and values
- Added tests, @stijnmoreels since DataSetParameters property is internal, not sure how I could assert that if a dataset parameter is added to a not empty dictionary of parameters, it is added to the dictionary and not overridden. Any suggestions for this please? Should I expose the RunDataFlowOptions.DataSetParameters via a method?
=> feat: Added dataset parameters to dataflow debug settings and added tests

src/Arcus.Testing.Tests.Integration/Storage/TemporaryTableTests.cs, src/Arcus.Testing.Tests.Unit/Logging/InMemoryLogSinkTests.cs, src/Arcus.Testing.Tests.Unit/Logging/LoggerSinkConfigurationExtensionsTests.cs
* Disable NuGet Serilog warnings on deprecated tests.
* Add default switch case for table tests.
=> chore: disable/fix warnings in tests

src/Arcus.Testing.Core/Arcus.Testing.Core.csproj, src/Arcus.Testing.Integration.DataFactory/Arcus.Testing.Integration.DataFactory.csproj, src/Arcus.Testing.Integration.DataFactory/DataFlowRunResult.cs, src/Arcus.Testing.Logging.Core/Arcus.Testing.Logging.Core.csproj, src/Arcus.Testing.Security.Providers.InMemory/Arcus.Testing.Security.Providers.InMemory.csproj, src/Arcus.Testing.Storage.Blob/Arcus.Testing.Storage.Blob.csproj, src/Arcus.Testing.Storage.Cosmos/Arcus.Testing.Storage.Cosmos.csproj, src/Arcus.Testing.Storage.Table/Arcus.Testing.Storage.Table.csproj, src/Arcus.Testing.Tests.Core/Arcus.Testing.Tests.Core.csproj, src/Arcus.Testing.Tests.Integration/Arcus.Testing.Tests.Integration.csproj, src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj
* Use v10.0.0 now as upperbound package version for Microsoft package to allow easier support for the most recent v9.x package.
* Use the most recent Az.Identity package to remove (some of the) security vulnerabilities in transient packages.
=> chore: manual update microsoft az packages

src/Arcus.Testing.Assert/Arcus.Testing.Assert.csproj, src/Arcus.Testing.Core/Arcus.Testing.Core.csproj, src/Arcus.Testing.Integration.DataFactory/Arcus.Testing.Integration.DataFactory.csproj, src/Arcus.Testing.Logging.Core/Arcus.Testing.Logging.Core.csproj, src/Arcus.Testing.Logging.MSTest/Arcus.Testing.Logging.MSTest.csproj, src/Arcus.Testing.Logging.NUnit/Arcus.Testing.Logging.NUnit.csproj, src/Arcus.Testing.Logging.Xunit/Arcus.Testing.Logging.Xunit.csproj, src/Arcus.Testing.Messaging.Pumps.EventHubs/Arcus.Testing.Messaging.Pumps.EventHubs.csproj, src/Arcus.Testing.Messaging.Pumps.ServiceBus/Arcus.Testing.Messaging.Pumps.ServiceBus.csproj, src/Arcus.Testing.Security.Providers.InMemory/Arcus.Testing.Security.Providers.InMemory.csproj, src/Arcus.Testing.Storage.Blob/Arcus.Testing.Storage.Blob.csproj, src/Arcus.Testing.Storage.Cosmos/Arcus.Testing.Storage.Cosmos.csproj, src/Arcus.Testing.Storage.Table/Arcus.Testing.Storage.Table.csproj
Don't let a NuGet audit warning (could be vulnerability low - critical) fail the compilation, as we do not have the budget to hotfix every NuGet warnings as quickly as possible.
=> chore: don't treat nuget warnings as errors

src/Arcus.Testing.Storage.Table/TemporaryTable.cs
Fixes to the correct `[Test:Setup]` log tag in the `TemporaryTable`.
=> fix: correct exception message tag

src/Arcus.Testing.Core/DisposableCollection.cs, src/Arcus.Testing.Integration.DataFactory/TemporaryDataFlowDebugSession.cs, src/Arcus.Testing.Storage.Blob/TemporaryBlobContainer.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbCollection.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlContainer.cs, src/Arcus.Testing.Storage.Table/TemporaryTable.cs
Use `LogDebug` for all setup/teardown actions, use `LogTrace` for additional event actions besides the general setup/teardown, use `LogInformtation` for global operations.
=> chore: streamline loglevels throughout test fixtures

src/Arcus.Testing.Logging.Core/Arcus.Testing.Logging.Core.csproj, src/Arcus.Testing.Logging.Core/CustomLoggerProvider.cs, src/Arcus.Testing.Logging.Core/InMemoryLogSink.cs, src/Arcus.Testing.Logging.Core/InMemoryLogger.cs, src/Arcus.Testing.Logging.Core/InMemoryLoggerT.cs, src/Arcus.Testing.Logging.Core/LogEntry.cs, src/Arcus.Testing.Logging.MSTest/Arcus.Testing.Logging.MSTest.csproj, src/Arcus.Testing.Logging.MSTest/Extensions/ILoggerBuilderExtensions.cs, src/Arcus.Testing.Logging.MSTest/Extensions/LoggerSinkConfigurationExtensions.cs, src/Arcus.Testing.Logging.MSTest/MSTestLogEventSink.cs, src/Arcus.Testing.Logging.NUnit/Arcus.Testing.Logging.NUnit.csproj, src/Arcus.Testing.Logging.NUnit/Extensions/ILoggerBuilderExtensions.cs, src/Arcus.Testing.Logging.Xunit/Arcus.Testing.Logging.Xunit.csproj, src/Arcus.Testing.Logging.Xunit/Extensions/ILoggerBuilderExtensions.cs
The logger core package is actually deprecated in the sense that we don't/shouldn't support these very technical in-memory stuff, in favor of having test framework-specific packages.
The core package was made to not create a NuGet package anymore before, but that caused issues related to project references of the other packages. Therefore, we still have to generate such a package until v2.0.
All functionality in the core package is made deprecated here.
=> fix: deprecate logger core package

docs/src/css/custom.css, docs/src/prism/dark.js, docs/src/prism/light.js
SonarCloud notified us about some reliability & maintainability issues regarding the frontend files.
* Font-families should have a generic fallback font;
* Best use `const`/`let` instead of `var.
This PR fixes that.
=> fix(docs): frontend sonar cloud issues

src/Arcus.Testing.Integration.DataFactory/TemporaryDataFlowDebugSession.cs
Some slashes where added at the end of the `<remarks/>` XML code tag in the DataFactory test fixture. This PR removes them.
=> chore(df): remove unnecessary xml slahes in DataFactory test fixture

docs/preview/03-Features/04-Azure/04-Storage/02-cosmos.mdx, src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbCollection.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbDocument.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlContainer.cs
Improve both the feature documentation and the XML code docs to show how the CosmosDb's `ResourceIdentifier` can be constructed easily by using their respective types (i.e. `CosmosDBAccountResource.CreateResourceIdentifier`).
✅ This helps a little more to construct resource ID's than to mention: `ResourceIdentifier id = ...`.
=> docs(cosmos): improve cosmosdb resource (id) construction

src/Arcus.Testing.Tests.Integration/Arcus.Testing.Tests.Integration.csproj, src/Arcus.Testing.Tests.Integration/Core/Fixture/TemporaryDirectory.cs, src/Arcus.Testing.Tests.Integration/Core/Fixture/TemporaryFile.cs, src/Arcus.Testing.Tests.Integration/Core/Fixture/TemporaryFileEdit.cs, src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj
Remove, consolidate and upgrade NuGet packages in the test projects.
🗑️ Remove Guard.NET package.
🗑️ Remove transient packages that were explicitly referenced.
⬆️ Upgrade Bogus;
⬆️ Upgrade Coverlet;
⬆️ Upgrade Moq;
⬆️ Upgrade Microsoft Test SDK;
=> chore(deps): upgrade test project packages

docs/preview/03-Features/04-Azure/06-Integration/01-data-factory.mdx, src/Arcus.Testing.Integration.DataFactory/TemporaryDataFlowDebugSession.cs
Improve both the feature documentation as the XML code docs of the DataFactory test components by explaining how `DataFactoryResource`s and their `ResourceIdentifier`s can be constructed by using their respective type (i.e. `DataFactoryResource.CreateResourceIdenfier`). 
✅ This helps a little more to construct resource ID's than to mention: `ResourceIdentifier id = ...`.
=> docs(df): improve data-factory guide on resource (id) construction

docs/preview/03-Features/04-Azure/04-Storage/02-cosmos.mdx, src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlContainer.cs, src/Arcus.Testing.Tests.Integration/Storage/TemporaryNoSqlContainerTests.cs, src/Arcus.Testing.Tests.Unit/Storage/NoSqlItemFilterTests.cs, src/Arcus.Testing.Tests.Unit/Storage/TemporaryNoSqlContainerOptionsTests.cs
Mark the `NoSqlFilter` as deprecated in favor of a more dev-friendly direct predicate function.
Developers are used to having delegates `Func<...>` when they see `Where`/`Match` functions. Having an extra type only overcomplicates things.
Closes #261
=> chore(cosmos): deprecate unnecessary az cosmos nosql functionality

docs/preview/03-Features/04-Azure/04-Storage/01-storage-account.mdx, src/Arcus.Testing.Storage.Table/TemporaryTable.cs, src/Arcus.Testing.Tests.Integration/Storage/TemporaryTableTests.cs, src/Arcus.Testing.Tests.Unit/Storage/TemporaryTableTests.cs
Deprecate unnecessary functionality that adds an additional layer of abstraction for the `TemporaryTable` filters.
Developers are used to having delegates `Func<...>` when they see `Where`/`Match` functions. Having an extra type only overcomplicates things.
Closes #259
=> chore(table): deprecate unnecessary az table functionality

src/Arcus.Testing.Tests.Integration/Configuration/AzureEnvironment.cs, src/Arcus.Testing.Tests.Integration/Configuration/ServicePrincipal.cs, src/Arcus.Testing.Tests.Integration/Integration/DataFactory/Configuration/DataFactoryConfig.cs, src/Arcus.Testing.Tests.Integration/Integration/DataFactory/Fixture/TemporaryDataFactoryDataFlow.cs, src/Arcus.Testing.Tests.Integration/Storage/Configuration/CosmosDbConfig.cs, src/Arcus.Testing.Tests.Integration/Storage/Fixture/MongoDbTestContext.cs, src/Arcus.Testing.Tests.Integration/Storage/Fixture/NoSqlTestContext.cs, src/Arcus.Testing.Tests.Integration/Storage/TemporaryMongoDbCollectionTests.cs, src/Arcus.Testing.Tests.Integration/Storage/TemporaryMongoDbDocumentTests.cs, src/Arcus.Testing.Tests.Integration/Storage/TemporaryNoSqlContainerTests.cs
Introduce `AzureEnvironment` test config subsection to eliminate duplication and centralize configuration in the integration test project.
✅ Centralizing this test config subsection will help with change as there is now only a single place where the subscription ID and resource group name is retrieved from the `appsettings.json`.
=> chore(setup): add az env test config

.github/renovate.json
Adds the `renovate.json` file to the repository with custom configuration so that Renovate does not create a PR, but rather updates the 'Dependeny Dashboard' GitHub issue. This is a better option than to create PR's as in library development, one has to take backwards compatibility into account and cannot go through with every update at once. To minimize the noise, having the dependency dashboard allows us to update the dependencies at our own pace, yet be notified of updates.
👀 Oh, and security updates are still being taken care of by the built-in Dependabot in GitHub. There a security notification will be raised.
=> chore(deps): add `renovate.json` w/ dependency dashboard issue

.github/workflows/bump-docs-version.yml
The `cd docs` command did not run together with the other GitHub tasks in the workflow definition.
This PR combines the NPM commands into a single task to keep track of the changed directory.
=> fix(workflow): combine GitHub npm task into 1 of auto-bump docs version workflow

src/Arcus.Testing.Tests.Integration/Storage/TemporaryNoSqlContainerTests.cs
The `CreateTempNoSqlContainerWithCleanMatchingOnSetup_WhenExistingItem_SucceedsByCleaningSubset` integration test was using the wrong NoSql item to match during the 'setup' phase, making the test sometimes fail.
=> fix(nosql): partition key match integration test

.github/renovate.json
The `renovate.json` has some additional options that we can use to improve the dependency dashborad GitHub issue.
* Adds `dependencies` and `management` labels to the created PR's so that it always clear that this should be taken up by the code-owners.
* Use `rangeStrategy:widen` to 'widen' any package ranges we have ('increase' was not valid).
* Use a configured title for the issue, so that it is more clear what this is (includes 'Renovate' in the title).
* Adds a `$schema` property, so that we have intelesense when editing locally.
=> chore(renovate): correct config w/ rangeStrategy, issue title & labels

build/templates/resource-group.bicep
Fixes the SonarCloud S6956 issue in the `resource-group.bicep` by correcing the order of elements.
=> fix(ioc): S6956 in bicep resource group

.github/renovate.json
The Renovate configuration states that no wildcards can be used for ignored dependencies and the `/samples` folder also does not seem to be ignored by the current config.
This PR fixes that by removing wildcards in favor of an explicit package name reference, plus using a more simpler `/samples/**` path.
=> chore(deps): correct `renovate.json` with correct syntax for ignored deps & paths

build/templates/trigger-bump-docs-version.yml
While the Azure DevOps version parameter is without a `v` prefix, the feature documentation needs that prefix. This PR adds the `v` before the `$(Build.BuildNumber)`, so that it gets correctly passed to the GitHub action.
=> fix(docs): auto-bump version with 'v' prefix

src/Arcus.Testing.Storage.Blob/TemporaryBlobContainer.cs, src/Arcus.Testing.Storage.Blob/TemporaryBlobFile.cs, src/Arcus.Testing.Tests.Integration/Storage/TemporaryBlobFileTests.cs, src/Arcus.Testing.Tests.Unit/Storage/TemporaryBlobFileTests.cs
> 👉 Since we have released all our deprecated messages, we can prepare for v2.0, meaning: removing stuff for real.
This PR removes the unncessary/duplicated-functionality options on the temporary Azure Blob file test fixture, as this can be handled at container-level.
Relates to #212
=> chore(blob): remove temp blob file options

src/Arcus.Testing.Storage.Table/TemporaryTable.cs, src/Arcus.Testing.Tests.Integration/Storage/TemporaryTableTests.cs, src/Arcus.Testing.Tests.Unit/Storage/TemporaryTableTests.cs
> 👉 Since we have released all our deprecated messages, we can prepare for v2.0, meaning: removing stuff for real.
This PR removes the unncessary/duplicated-functionality options on the temporary Azure Table entity filter, as this can be handled with `Func<TableEntity, bool>` delegates.
Relates to #259
=> chore(table): remove temp table entity filter

src/Arcus.Testing.Assert/Arcus.Testing.Assert.csproj, src/Arcus.Testing.Core/Arcus.Testing.Core.csproj, src/Arcus.Testing.Integration.DataFactory/Arcus.Testing.Integration.DataFactory.csproj, src/Arcus.Testing.Messaging.ServiceBus/Arcus.Testing.Messaging.ServiceBus.csproj, src/Arcus.Testing.Storage.Blob/Arcus.Testing.Storage.Blob.csproj, src/Arcus.Testing.Storage.Cosmos/Arcus.Testing.Storage.Cosmos.csproj, src/Arcus.Testing.Storage.Table/Arcus.Testing.Storage.Table.csproj, src/Arcus.Testing.Tests.Core/Arcus.Testing.Tests.Core.csproj, src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj
> 👉 Since we've already published our deprecation messages, we can safely remove this target framework.
Starting from v2.0, .NET 6 will be removed from the supported target frameworks. .NET 6 is not removed here from the logging libraries, as they will be migrated seperately (they also need to remove their link to our logging.core library).
=> chore(deps): remove net6.0 target framework from all but logging libraries

src/Arcus.Testing.Logging.NUnit/Extensions/ILoggerBuilderExtensions.cs
With multiple logger providers, it is sometimes the case that you want to filter certain logs based on category with specific log levels. To do this for custom logger providers, you can set the `[ProviderAlias(...)]` attribute.
This PR sets this attribute to the custom logger provider of the NUnit logging package.
This would allow stuff like:
```json
{
"Logging": {
"LogLevel": {
"Default": "Information"
},
"NUnit": {
"LogLevel": {
"Default": "Trace"
}
}
}
}
```
Relates to #242
=> feat(logging.nunit): add provider alias to nunit logger provider

src/Arcus.Testing.Logging.MSTest/Extensions/ILoggerBuilderExtensions.cs
With multiple logger providers, it is sometimes the case that you want to filter certain logs based on category with specific log levels. To do this for custom logger providers, you can set the `[ProviderAlias(...)]` attribute.
This PR sets this attribute to the custom logger provider of the MSTest logging package.
This would allow stuff like:
```json
{
"Logging": {
"LogLevel": {
"Default": "Information"
},
"MSTest": {
"LogLevel": {
"Default": "Trace"
}
}
}
}
```
Relates to #242
=> feat(logging.mstest): add provider alias to mstest logger provider

docs/preview/03-Features/03-logging.mdx
> 👉 Since we have released all our deprecated messages, we can prepare for v2.0, meaning: removing stuff for real.
This PR removes the mentioning of th logging.core package and its in-memory/Serilog functionality from the logging feature documentation.
Relates to #212
=> docs(logging): remove logging.core from logging feature docs

src/Arcus.Testing.Core/ResourceDirectory.cs, src/Arcus.Testing.Core/TestConfig.cs
Adds `[Test] ` tags to the test-specific exceptions that are thrown by our test core components. This will make it more clear that the failure is happening to something 'test' related, instead of something that is 'not expected'.
=> chore(core): add exception test tags in core library

docs/versioned_docs/version-v1.3.0/04-Guidance/migrate-from-testing-framework-to-arcus-testing-v1.0.mdx
As described in #330 and the like, the custom types for filtering values in temporary storage systems are deprecated, in favor of using delegate filters.
This PR makes sure that we also use these delegate filters in the migration guide.
=> docs(migration.v1.0): use delegate filters in migration guide v1.0

docs/preview/03-Features/01-core.md, src/Arcus.Testing.Core/ResourceDirectory.cs, src/Arcus.Testing.Tests.Integration/Core/ResourceDirectoryTests.cs, src/Arcus.Testing.Tests.Unit/Assert_/AssertJsonTests.cs
When building large paths for test resources, many `.WithSubDirectory(...)` calls can be a lot of noise. This PR overrides the `/` operator to act as a path seperator for resource directories.
Closes #341
=> feat(core): add user-friendly operators to resource directory

docs/preview/04-Guidance/migrate-from-testing-framework-to-arcus-testing-v1.0.mdx
It came to our attention (see #338) that the migration guide to v1 does not explicitly mention XSLT extension objects. This could cause some disruption when migrating to Arcus.Testing.
This PR adds a small paragraph to explain how the same XSLT arguments can be used with `AssertXslt.TransformTo...` overloads.
Relates to #338
=> docs(xslt.migration): add extension objects to the v1 migration guide

src/Arcus.Testing.Logging.MSTest/Arcus.Testing.Logging.MSTest.csproj, src/Arcus.Testing.Logging.NUnit/Arcus.Testing.Logging.NUnit.csproj, src/Arcus.Testing.Logging.Xunit/Arcus.Testing.Logging.Xunit.csproj
> 👉 Since we already published our deprecating messages, we can remove stuff for real.
Microsoft's support for .NET 6 has ended, we should therefore remove it from our currently supported target frameworks. A previous PR #331 already removed it in the other non-logging projects, this PR removes it in the logging projects.
=> chore(logging): remove net6.0 target framework from logging projects

build/ci-build.yml
Since we use the `ubuntu-latest` in our CI pipelines, it notified us that the current approach on pushing NuGet packages to our MyGet feed (which gets pushed on every open PR), is now not working anymore with the newest Ubuntu release (v24.04).
Because of this, and the fact that we use YAML templates to streamline throughout Arcus repo's, we are left with a broken CI build.
This PR removes the YAML template in favor of a custom `dotnet nuget` command, as this will both fix the CI build, as well as removing a bit of unnecessary relationship with other Arcus repo's. It allows for Arcus repositories to grow more on their own, and to fix issues (like these) more quicker, without the overhead of other repo's. The downside, is that there might be some duplicated code, but since the amount of …
=> fix(ci): use custom `dotnet nuget` to push PR previews to MyGet

docs/preview/03-Features/01-core.md
The `ResourceDirectory` has a `.WithSubDirectory(...)` method, but this was wrongly mentioned in the feature docs.
This PR fixes that.
Follow-up PR of #344
=> fix(docs.core): use correct resource directory method

src/Arcus.Testing.Storage.Table/TemporaryTable.cs, src/Arcus.Testing.Storage.Table/TemporaryTableEntity.cs
improve the handling of null or whitespace arguments by using the new `ArgumentException.ThrowIfNullOrWhiteSpace` method. These changes help to simplify the code and make it more readable.
=> chore(table): use net8.0 arg constructs in table library

src/Arcus.Testing.Messaging.ServiceBus/ServiceBusMessageFilter.cs, src/Arcus.Testing.Messaging.ServiceBus/TemporaryQueue.cs, src/Arcus.Testing.Messaging.ServiceBus/TemporaryTopic.cs, src/Arcus.Testing.Messaging.ServiceBus/TemporaryTopicSubscription.cs
The primary change is the replacement of manual argument validation with the use of built-in exception methods for cleaner and more concise code.
=> chore(service-bus): use net8.0 arg constructs in messaging library

src/Arcus.Testing.Logging.MSTest/MSTestLogger.cs, src/Arcus.Testing.Logging.NUnit/NUnitTestLogger.cs, src/Arcus.Testing.Logging.Xunit/XunitTestLogger.cs, src/Arcus.Testing.Tests.Unit/Logging/MSTestLoggerTests.cs
Use the new .NET 8 constructs for argument checking throughout the logging libraries, streamlining along the way. Plus, adding the missing `MSTestLogger<TCategoryName>` (#364).
Relates to #356 
Closes #364
=> chore(logging): streamline w/ net8.0 constructs in logging

src/.editorconfig
Use `var` only when type is apparent.
➡️ Added this code style line to the `.editorconfig` file, as this was already mentioned in the general Arcus code style.
Follow-up #275
=> chore(style): use 'var' when type is apparent

src/Arcus.Testing.Core/AsyncDisposable.cs, src/Arcus.Testing.Core/DisposableCollection.cs, src/Arcus.Testing.Core/ResourceDirectory.cs, src/Arcus.Testing.Core/TemporaryEnvironmentVariable.cs, src/Arcus.Testing.Core/TestConfig.cs
Uses the new .NET 8 constructs to argument-check parameters, together with additional streamlining on the links to the feature documentation and including default values in the XML code docs.
Relates to #356
=> chore(core): streamline w/ net8.0 constructs in core

docs/preview/03-Features/04-Azure/04-Storage/02-cosmos.mdx
Rename from `Arcus.Testing.Storage.CosmosDb`  to `Arcus.Testing.Storage.Cosmos` package
=> fix(docs): Update invalid package name for CosmosDb

docs/preview/03-Features/04-Azure/04-Storage/01-storage-account.mdx, src/Arcus.Testing.Storage.Table/TemporaryTable.cs, src/Arcus.Testing.Storage.Table/TemporaryTableEntity.cs
Let's already introduce the new 'upsert entity' renaming for v2.0, so that the new feature documentation already points to the right methods.
Relates to #378
=> chore(table): introduce 'upsert entity' renaming

docs/preview/03-Features/04-Azure/04-Storage/02-cosmos.mdx, src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbCollection.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbDocument.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlContainer.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlItem.cs
Let's already introduce the new `Upsert[Item/Document]Async` in the `.Cosmos` package for v2, so that the v3 feature documentation is already pointing to the new ones.
Relates to #378
=> chore(cosmos): introduce 'upsert doc/item' renaming

docs/preview/02-getting-started.md
The 'getting started' page contained some typo's and some duplicate meaning (like: libraries <> packages).
This PR fixes that.
=> docs(getting_started): typo's, simplified and correct language

src/Arcus.Testing.Storage.Blob/TemporaryBlobContainer.cs
The `TemporaryBlobContainerOptions` still had the `blob's names` from the old removed/deprecated `BlobNameFilter` type (#256) in the XML code docs of the matched filters.
This PR fixes that by specifying it is actually the `blobs` to match during setup/teardown, not only the name.
Closes #377
=> chore(blob): correct xml code docs for temp blob container options match filters

src/Arcus.Testing.Core/ResourceDirectory.cs
When throwing a `DirectoryNotFoundException` on a sub-resource directory, only the root directory path was included.
This PR includes the sub-directory path for better defect localization.
Closes #373
=> chore(core): use sub-directory in dir-not-found exception

docs/preview/04-Guidance/migrate-from-v1-to-v2.md
To make the transition from v1 to v2 a bit smoother, this PR adds a migration guide that summarizes the changes in deprecated functionality and the current supported NuGet packages. The deprecation messages should've made it already clear, but it never hurts to have this documented somewhere.
Relates to #326 , #330 , #319 , #321 , #332 , #318, #327...
=> docs(v2): add migration guide for v1-v2

CONTRIBUTING.md, README.md, src/Arcus.Testing.Tests.Integration/Arcus.Testing.Tests.Integration.csproj, src/Arcus.Testing.Tests.Integration/Configuration/ServicePrincipal.cs, src/Arcus.Testing.Tests.Integration/Fixture/TemporaryManagedIdentityConnection.cs, src/Arcus.Testing.Tests.Integration/Integration/DataFactory/RunDataFlowTests.cs, src/Arcus.Testing.Tests.Integration/IntegrationTest.cs, src/Arcus.Testing.Tests.Integration/Messaging/Fixture/ServiceBusTestContext.cs, src/Arcus.Testing.Tests.Integration/Storage/Fixture/BlobStorageTestContext.cs, src/Arcus.Testing.Tests.Integration/Storage/Fixture/MongoDbTestContext.cs, src/Arcus.Testing.Tests.Integration/Storage/Fixture/NoSqlTestContext.cs, src/Arcus.Testing.Tests.Integration/Storage/Fixture/TableStorageTestContext.cs, src/Arcus.Testing.Tests.Integration/appsettings.default.json
To make sure that both internal (Codit)/external (non-Codit) contributions happen more easily, this PR:
* Adds GitHub's `CONTRIBUTING.md` file that gives an overview of what people can do in case of bug/feature/idea.
* Adds an `default` authentication to the test suite, so that one can run integration tests locally outside of Codit/Arcus-deployed Azure resources.
=> feat(contrib): finalize internal/external contribution setup+docs

docs/preview/03-Features/04-Azure/04-Storage/01-storage-account.mdx, src/Arcus.Testing.Storage.File.Share/Arcus.Testing.Storage.File.Share.csproj, src/Arcus.Testing.Storage.File.Share/TemporaryShareDirectory.cs, src/Arcus.Testing.Storage.File.Share/TemporaryShareFile.cs, src/Arcus.Testing.Tests.Integration/Arcus.Testing.Tests.Integration.csproj, src/Arcus.Testing.Tests.Integration/Storage/TemporaryShareDirectoryTests.cs, src/Arcus.Testing.Tests.Integration/Storage/TemporaryShareFileTests.cs, src/Arcus.Testing.sln
Adds the initial test fixtures for the Azure File share storage:
* `TemporaryShareDirectory`: to temporary create a directory on the share;
* `TemporaryShareFile`: to temporary create a file on the directory.
Closes #249
=> feat(storage): add initial file-share dir+file fixtures

src/Arcus.Testing.Assert/AssertCsv.cs, src/Arcus.Testing.Tests.Unit/Assert_/AssertCsvTests.cs
Stricten the `AssertCsvTest` so that we know that both specific headers (without ignoring) are shown in the test output upon a row failure (meaning: a failing within the values of the row).
The problem was that the previous PR #382 altered the final `HeaderNames` when loading the CSV, but this same one was used when constructing the final 'row difference'. This PR removes all references to the 'assertion result' and solely uses the `_originalCsv` to construct differences at row level.
Follow-up of #382
=> fix(assert.csv): show correct failed headers w/ ignored coll

docs/preview/03-Features/04-Azure/06-Integration/01-data-factory.mdx, src/Arcus.Testing.Integration.DataFactory/TemporaryDataFlowDebugSession.cs, src/Arcus.Testing.Tests.Integration/Integration/DataFactory/Fixture/TemporaryDataFactoryDataFlow.cs, src/Arcus.Testing.Tests.Integration/Integration/DataFactory/RunDataFlowTests.cs, src/Arcus.Testing.Tests.Unit/Integration/DataFactory/RunDataFlowTests.cs
In DataFactory, one or multiple flowlets can be present in a DataFlow. A flowlet is a re-usable piece of DataFlow. To start a debug session for a DataFlow containing a flowlet, we must first add the flowlet(s) to the debugPackageContent DataFlows (a flowlet is derived from a dataflow).
This adds the possibility to add flowlet(s) to the DataFlow debug session by using `options.AddFlowlet("<flowlet-name>");` feature.
=> feat(integration): add support for dataFactory DataFlows which contain Flowlets

src/Arcus.Testing.Core/Poll.cs, src/Arcus.Testing.Tests.Unit/Core/PollTests.cs
The combination of the new xUnit v3 testing framework and the additional polling tests created by #348 , made the current polling tests fail. Since these tests were also a bit harder to investigate if something failed, since they were grouped together, plus the nature of instable timeouts - it already helped a lot if the tests were split by category (direct/fluent, sync/async).
Furthermore, the `PollOptions` weren't always created 'fresh', which could cause disruption in a multi-polling scenario.
This PR both simplifies the tests for better defect localization, as well as fixes the `PollOptions` creation process.
=> fix(poll): use new `PollOptions` instance on each call

README.md
This PR uses the built-in GitHub Markdown 'Note' functionality in the repository root `README.md`, instead of the Markdown blockquote one. It makes it more visually attractive.
=> chore(readme): use github markdown note instead of blockquote

docs/preview/03-Features/04-Azure/05-Messaging/01-servicebus.mdx, docs/versioned_docs/version-v2.0.0/03-Features/04-Azure/05-Messaging/01-servicebus.mdx, docs/versioned_docs/version-v2.1.0/03-Features/04-Azure/05-Messaging/01-servicebus.mdx, src/Arcus.Testing.Messaging.ServiceBus/TemporaryTopicSubscription.cs, src/Arcus.Testing.Tests.Integration/Messaging/Fixture/ServiceBusTestContext.cs, src/Arcus.Testing.Tests.Integration/Messaging/TemporaryTopicSubscriptionTests.cs
The Azure Service Bus topic subscription rule functionality was not fully covered by the feature documentation as well as the tests. This PR fixes that, by enhancing the existing tests and adding dedicated failure scenarios.
> [!NOTE]
> The `Service bus` has been renamed to `Service Bus` as well in the docs, as to follow Microsoft's standards.
Follow-up of #96
=> fix(az.sb.topic.sub): add missing coverage for az sb topic sub rules

docs/preview/03-Features/04-Azure/04-Storage/01-storage-account.mdx, docs/versioned_docs/version-v2.0.0/03-Features/04-Azure/04-Storage/01-storage-account.mdx, docs/versioned_docs/version-v2.1.0/03-Features/04-Azure/04-Storage/01-storage-account.mdx, src/Arcus.Testing.Storage.Blob/TemporaryBlobContainer.cs, src/Arcus.Testing.Storage.Blob/TemporaryBlobFile.cs, src/Arcus.Testing.Storage.File.Share/TemporaryShareDirectory.cs, src/Arcus.Testing.Storage.File.Share/TemporaryShareFile.cs, src/Arcus.Testing.Storage.Table/TemporaryTable.cs
The test fixtures described for Azure Storage Account did not used the correct naming conventions (i.e. 'Blob Storage' instead of 'Blob storage').
This PR fixes those violations in both the code summary tags as well as the feature documentation.
Relates to #417
=> chore(az.storage): use microsoft naming for az storage account

src/Arcus.Testing.Messaging.ServiceBus/ServiceBusMessageFilter.cs, src/Arcus.Testing.Messaging.ServiceBus/TemporaryQueue.cs, src/Arcus.Testing.Messaging.ServiceBus/TemporaryTopic.cs
Use 'Service Bus' instead of 'Service bus' everywhere in the test fixtures (except the topic subscription, as that is done in #415).
Follow-up of #201
=> chore(az.sb): use microsoft naming for az service-bus

docs/preview/03-Features/04-Azure/04-Storage/02-cosmos.mdx, docs/versioned_docs/version-v2.0.0/03-Features/04-Azure/04-Storage/02-cosmos.mdx, docs/versioned_docs/version-v2.1.0/03-Features/04-Azure/04-Storage/02-cosmos.mdx, src/Arcus.Testing.Storage.Cosmos/Arcus.Testing.Storage.Cosmos.csproj, src/Arcus.Testing.Storage.Cosmos/MongoDbConnection.cs, src/Arcus.Testing.Storage.Cosmos/NoSqlExtraction.cs, src/Arcus.Testing.Storage.Cosmos/NoSqlItemParser.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbCollection.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbDocument.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlContainer.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlItem.cs
We used different naming conventions for Microsoft products in our code summary tags and feature documentation (i.e. `MongoDb` instead of `MongoDB`).
This PR tries to streamline these differences so that both the recent/preview documentation, logging, exception messages... all mention these products by their correct name.
Relates to #417
=> chore(az.cosmos.db): use microsoft naming for az cosmos db

src/Arcus.Testing.Storage.Blob/Arcus.Testing.Storage.Blob.csproj, src/Arcus.Testing.Storage.File.Share/Arcus.Testing.Storage.File.Share.csproj, src/Arcus.Testing.Storage.Table/Arcus.Testing.Storage.Table.csproj
In a previous PR #418, the Microsoft naming conventions for Microsoft products were fixed in the feature documentation and code summary tags, but it was forgotten to change in the package description of those libraries.
This PR streamlines these naming conventions in the Azure Storage Account-related packages.
Relates to #417
=> chore(az.storage): use microsoft naming for storage package descriptions

build/deploy-test-resources.yml, build/templates/test-resources.bicep, docs/preview/03-Features/01-core.md, docs/preview/03-Features/04-Azure/04-Storage/02-cosmos.mdx, docs/preview/03-Features/04-Azure/06-Integration/01-data-factory.mdx, docs/preview/04-Guidance/migrate-from-testing-framework-to-arcus-testing-v1.0.mdx, docs/preview/04-Guidance/migrate-from-v1-to-v2.md, docs/versioned_docs/version-v2.0.0/03-Features/01-core.md, docs/versioned_docs/version-v2.0.0/03-Features/04-Azure/04-Storage/02-cosmos.mdx, docs/versioned_docs/version-v2.0.0/03-Features/04-Azure/06-Integration/01-data-factory.mdx, docs/versioned_docs/version-v2.0.0/04-Guidance/migrate-from-testing-framework-to-arcus-testing-v1.0.mdx, docs/versioned_docs/version-v2.0.0/04-Guidance/migrate-from-v1-to-v2.md, docs/versioned_docs/version-v2.1.0/03-Features/01-core.md, docs/versioned_docs/version-v2.1.0/03-Features/04-Azure/04-Storage/02-cosmos.mdx, docs/versioned_docs/version-v2.1.0/03-Features/04-Azure/06-Integration/01-data-factory.mdx, docs/versioned_docs/version-v2.1.0/04-Guidance/migrate-from-testing-framework-to-arcus-testing-v1.0.mdx, docs/versioned_docs/version-v2.1.0/04-Guidance/migrate-from-v1-to-v2.md
Not all source files already used the Microsoft naming conventions for their products. This is a follow-up PR for previous PR's related to #417 .
This final PR should finally streamline this naming convention throughout.
Closes #417
=> chore(mcr): use microsoft naming conventions throughout (follow-up)

src/Arcus.Testing.Storage.Cosmos/MongoDbConnection.cs, src/Arcus.Testing.Tests.Integration/Storage/TemporaryBlobContainerTests.cs, src/Arcus.Testing.Tests.Integration/Storage/TemporaryShareDirectoryTests.cs, src/Arcus.Testing.Tests.Integration/Storage/TemporaryShareFileTests.cs
Since some components were added before we introduced `.editorconfig`, there were still some files left that violated - and so, halted us from using an automated - code style workflow.
This PR applies the current rules to the storage components.
Relates to #432
=> chore(style): apply .editorconfig on storage components

src/Arcus.Testing.Tests.Unit/Assert_/AssertXsltTests.cs, src/Arcus.Testing.Tests.Unit/Assert_/Fixture/TestJson.cs, src/Arcus.Testing.Tests.Unit/Assert_/Fixture/TestXml.cs
Since some components were added before we introduced `.editorconfig`, there were still some files left that violated - and so, halted us from using an automated - code style workflow.
This PR applies the current rules to the assert components.
Relates to #432
=> chore(style): apply .editorconfig on assert components

src/Arcus.Testing.Messaging.ServiceBus/Arcus.Testing.Messaging.ServiceBus.csproj, src/Arcus.Testing.Messaging.ServiceBus/ServiceBusMessageFilter.cs, src/Arcus.Testing.Messaging.ServiceBus/TemporaryQueue.cs, src/Arcus.Testing.Messaging.ServiceBus/TemporaryTopic.cs, src/Arcus.Testing.Messaging.ServiceBus/TemporaryTopicSubscription.cs
Applies the recommended code analysis rules for Roslyn analyzers in the `.ServiceBus` library. This is mostly about placing the log message templates in 'source generated message templates'. Mostly marketed as being 'more performant', but in our case it also helps with maintaining/centralizing log message templates (setup/teardown format).
=> chore(analysis): applied code analysis results in service bus

src/Arcus.Testing.Storage.Cosmos/Arcus.Testing.Storage.Cosmos.csproj, src/Arcus.Testing.Storage.Cosmos/MongoDbConnection.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbCollection.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryMongoDbDocument.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlContainer.cs, src/Arcus.Testing.Storage.Cosmos/TemporaryNoSqlItem.cs
Applies the recommended code analysis rules for Roslyn analyzers in the `.Cosmos` library. This is mostly about placing the log message templates in 'source generated message templates'. Mostly marketed as being 'more performant', but in our case it also helps with maintaining/centralizing log message templates (setup/teardown format).
=> chore(analysis): applied code analysis results in cosmos

src/Arcus.Testing.Storage.File.Share/Arcus.Testing.Storage.File.Share.csproj, src/Arcus.Testing.Storage.File.Share/TemporaryShareDirectory.cs, src/Arcus.Testing.Storage.File.Share/TemporaryShareFile.cs
Applies the recommended code analysis rules for Roslyn analyzers in the `.File.Share` library. This is mostly about placing the log message templates in 'source generated message templates'. Mostly marketed as being 'more performant', but in our case it also helps with maintaining/centralizing log message templates (setup/teardown format).
=> chore(analysis): applied code analysis results in files

src/Arcus.Testing.Integration.DataFactory/Arcus.Testing.Integration.DataFactory.csproj, src/Arcus.Testing.Integration.DataFactory/DataFlowRunResult.cs, src/Arcus.Testing.Integration.DataFactory/TemporaryDataFlowDebugSession.cs
Applies the recommended code analysis rules for Roslyn analyzers in the `.DataFactory` library. This is mostly about placing the log message templates in 'source generated message templates'. Mostly marketed as being 'more performant', but in our case it also helps with maintaining/centralizing log message templates (setup/teardown format).
=> chore(analysis): applied code analysis results in data factory

src/Arcus.Testing.Tests.Integration/XunitV2Using.cs
We've added an empty namespace that was used in the old xUnit v2 to limit the PR changes during the migration. This namespace is now not used anymore throughout the tests, so we can remove it.
Relates to #269
=> chore(xunit.v3): remove empty namespace to finalize xunit v3 migration

src/Arcus.Testing.Tests.Core/Arcus.Testing.Tests.Core.csproj
The old .NET 6, we were forced to add a dedicated System HTTP package in our test infrastructure. This is now unnecessary, so we can remove the package.
=> chore(deps): remove unnecessary system http package

src/Arcus.Testing.Integration.DataFactory/Arcus.Testing.Integration.DataFactory.csproj, src/Arcus.Testing.Integration.DataFactory/DataFlowRunResult.cs, src/Arcus.Testing.Integration.DataFactory/TemporaryDataFlowDebugSession.cs, src/Arcus.Testing.Tests.Integration/Integration/DataFactory/RunDataFlowTests.cs, src/Arcus.Testing.Tests.Integration/Integration/DataFactory/TemporaryDataFlowDebugSessionTests.cs
This PR applies several .NET and Roslyn recommendations in the Data Factory project:
* Use `.ConfigureAwait(false)` for asynchronous operations;
* Make multiple `.Dispose(Async)` calls redundant.
Relates #429
=> chore(df): apply df roslyn async analyzer suggestions

src/Arcus.Testing.Core/DisposableCollection.cs, src/Arcus.Testing.Storage.File.Share/Arcus.Testing.Storage.File.Share.csproj, src/Arcus.Testing.Storage.File.Share/TemporaryShareDirectory.cs, src/Arcus.Testing.Storage.File.Share/TemporaryShareFile.cs, src/Arcus.Testing.Tests.Integration/Storage/TemporaryShareDirectoryTests.cs, src/Arcus.Testing.Tests.Integration/Storage/TemporaryShareFileTests.cs
Applies the Roslyn and .NET recommendations regarding asynchronous operations and disposable objects:
* Use `.ConfigureAwait(false)` in asynchronous operations;
Relates to #429
=> chore(fileshare): apply roslyn code analyzer suggestions

src/Arcus.Testing.Core/Arcus.Testing.Core.csproj, src/Arcus.Testing.Core/DisposableCollection.cs, src/Arcus.Testing.Core/ResourceDirectory.cs
Applies `All` Roslyn analyzers on `.Core` project.
Relates to #454
=> chore(core): apply roslyn analysers to core project

.github/workflows/codeql-analysis.yml, .github/workflows/dotnet-format.yml, build/variables/build.yml, samples/Arcus.Testing.Sample.TestingFrameworkMigration/Arcus.Testing.Sample.TestingFrameworkMigration.csproj, src/Arcus.Testing.Assert/Arcus.Testing.Assert.csproj, src/Arcus.Testing.Core/Arcus.Testing.Core.csproj, src/Arcus.Testing.Integration.DataFactory/Arcus.Testing.Integration.DataFactory.csproj, src/Arcus.Testing.Logging.MSTest/Arcus.Testing.Logging.MSTest.csproj, src/Arcus.Testing.Logging.NUnit/Arcus.Testing.Logging.NUnit.csproj, src/Arcus.Testing.Logging.Xunit.v3/Arcus.Testing.Logging.Xunit.v3.csproj, src/Arcus.Testing.Logging.Xunit/Arcus.Testing.Logging.Xunit.csproj, src/Arcus.Testing.Messaging.ServiceBus/Arcus.Testing.Messaging.ServiceBus.csproj, src/Arcus.Testing.Storage.Blob/Arcus.Testing.Storage.Blob.csproj, src/Arcus.Testing.Storage.Cosmos/Arcus.Testing.Storage.Cosmos.csproj, src/Arcus.Testing.Storage.File.Share/Arcus.Testing.Storage.File.Share.csproj, src/Arcus.Testing.Storage.Table/Arcus.Testing.Storage.Table.csproj, src/Arcus.Testing.Tests.Core/Arcus.Testing.Tests.Core.csproj, src/Arcus.Testing.Tests.Integration/Arcus.Testing.Tests.Integration.csproj, src/Arcus.Testing.Tests.Unit/Arcus.Testing.Tests.Unit.csproj
Move the .NET support window towards .NET 10 (currently preview). No breaking changes are there, we can simply add the number to the .csproj files.
Closes #452
=> chore(net10.0): add support for .net 10.0 throughout

src/Arcus.Testing.Core/DisposableCollection.cs
Since we changed the disposable retry in the `DisposableCollection` to use the `.ConfigureAwait(false)` construct, SonarQube incorrectly notes that some code is unreachable. This PR ignores this false positive on this line.
=> chore(core): disable sonar-qube false positive unreachable code

src/Arcus.Testing.Logging.MSTest/Arcus.Testing.Logging.MSTest.csproj, src/Arcus.Testing.Logging.MSTest/Extensions/ILoggerBuilderExtensions.cs, src/Arcus.Testing.Logging.MSTest/MSTestLogger.cs, src/Arcus.Testing.Logging.NUnit/Arcus.Testing.Logging.NUnit.csproj, src/Arcus.Testing.Logging.NUnit/Extensions/ILoggerBuilderExtensions.cs, src/Arcus.Testing.Logging.NUnit/NUnitTestLogger.cs, src/Arcus.Testing.Logging.Xunit.v3/Arcus.Testing.Logging.Xunit.v3.csproj, src/Arcus.Testing.Logging.Xunit.v3/Extensions/ILoggerBuilderExtensions.cs, src/Arcus.Testing.Logging.Xunit/Arcus.Testing.Logging.Xunit.csproj, src/Arcus.Testing.Logging.Xunit/Extensions/ILoggerBuilderExtensions.cs, src/Arcus.Testing.Logging.Xunit/XunitTestLogger.cs
Apply `All` the Roslyn analyzer rules to the logging projects.
Relates to #449
=> chore(logging): apply roslyn analysers to logging projects

src/Arcus.Testing.Logging.Xunit.v3/Arcus.Testing.Logging.Xunit.v3.csproj
Xunit has already moved on to a next release version, we better expand our window for it. This PR uses v4 as next threshold, since there were no issues with v3.
=> chore(logging): upgrade xunit v3 package dependency

src/Arcus.Testing.Tests.Integration/Fixture/TemporaryManagedIdentityConnection.cs, src/Arcus.Testing.Tests.Integration/Integration/DataFactory/RunDataFlowTests.cs, src/Arcus.Testing.Tests.Integration/Integration/DataFactory/TemporaryDataFlowDebugSessionTests.cs, src/Arcus.Testing.Tests.Integration/Messaging/Fixture/ServiceBusTestContext.cs, src/Arcus.Testing.Tests.Integration/Storage/Fixture/BlobStorageTestContext.cs, src/Arcus.Testing.Tests.Integration/Storage/Fixture/MongoDbTestContext.cs, src/Arcus.Testing.Tests.Integration/Storage/Fixture/NoSqlTestContext.cs, src/Arcus.Testing.Tests.Integration/Storage/Fixture/TableStorageTestContext.cs
Due to the full parallelization of the integration tests (see #476), we need to make sure that there are no shared test fixtures across the tests. It turns out that we have configured a managed identity connection for each test context, and since this is pointing to the same service principal, it could happen that it gets teared down while another test still needs it.
This PR moves the managed identity test fixture to an assembly test fixture, so that authentication is configured once and shared across the tests.
=> fix(test.auth): move managed identity as an assembly test fixture
